# -*- coding: utf-8 -*-
"""google-serp-scraper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wImDRlFjTvTIQCm4UrvCalgJN6tN464M
"""

# Scrapping BS4
from request import requests
from bs4 import BeautifulSoup

html = requests.get('https://www.basketball-reference.com/players/g/garneke01.html')
soup = BeautifulSoup(html, 'html.parser')
dado_1 = soup.find(class_ = ".important.special")
print(junto.text)

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
import csv

palavra_chave = input('Digite sua busca')
driver = webdriver.Chrome()
driver.get("https://www.google.com/")
assert "Google" in driver.title
barra_busca = driver.find_element(By.CLASS_NAME, "gLFyf")
barra_busca.send_keys (palavra_chave, Keys.RETURN)
try:
  tempo = WebDriverWait (driver,15).until(EC.presence_of_all_elements_located((By.CSS_SELECTOR,'.LC20lb.MBeuO.DKV0Md')))
  titulos = driver.find_elements(By.CSS_SELECTOR,'.LC20lb.MBeuO.DKV0Md')[:10]
  meta_titulo = driver.find_elements(By.CSS_SELECTOR, 'a.zReHs')[:10]
  lista_links = zip(titulos, meta_titulo)
  with open ('Google_top_10.csv','w', newline ='') as planilha:
    escritor_csv = csv.writer(planilha)
    for titulo, link in lista_links:
      escritor_csv.writerow([titulo.text,link.get_attribute('href')])
except TimeoutException:
  print ('Tempo esgotado')
driver.quit()